// This file was autogenerated by closure/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../app/boards/dataview.js', ['neutron.dashboard.boards.DataView'], ['goog.dom', 'neutron.dashboard.panes.Projects']);
goog.addDependency('../../../app/data_view_application.js', ['neutron.dashboard.DataViewApplication'], ['goog.dom', 'goog.events', 'goog.events.EventTarget', 'goog.events.EventType', 'neutron.dashboard.boards.DataView']);
goog.addDependency('../../../app/panes/projects.js', ['neutron.dashboard.panes.Projects'], ['goog.dom']);
