// This file was autogenerated by closure/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../app/data_view_applicaton.js', ['neutron.dashboard.DataViewApplication'], ['goog.dom']);
